# Generated by Django 5.0.2 on 2024-03-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_address_doctor_date_of_birth_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
