# Generated by Django 5.0.2 on 2024-02-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WEB', 'Website'), ('CHAT', 'Chatbot'), ('SOCIAL', 'Social Media'), ('CALL', 'Direct Call'), ('IVR', 'IVR')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('APPT', 'Appointment'), ('MED', 'Medical'), ('BILL', 'Billing'), ('OTHER', 'Other')], max_length=10)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROG', 'In-Progress'), ('RES', 'Resolved'), ('CLOSED', 'Closed')], max_length=10)),
                ('color_code', models.CharField(choices=[('A', 'Red'), ('B', 'Green'), ('C', 'Blue')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('source_details', models.CharField(blank=True, max_length=50, null=True)),
                ('ivr_option', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolution_time', models.DateTimeField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
