# Generated by Django 5.0.2 on 2024-03-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
        ('users', '0007_alter_staff_department_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='assigned_staff',
        ),
        migrations.AddField(
            model_name='query',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, to='users.staff'),
        ),
    ]
