# Generated by Django 5.0.2 on 2024-03-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_remove_query_assigned_staff_query_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='query_supporting_documents/'),
        ),
    ]
