# Generated by Django 5.0.2 on 2024-03-12 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_remove_query_follow_up_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resolution',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='resolution_supporting_documents/'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.query'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.querycategory'),
        ),
    ]
