# Generated by Django 5.0.2 on 2024-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_querycategory_resolution_supporting_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querycategory',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
