# Generated by Django 5.0.2 on 2024-03-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='followup_supporting_documents/'),
        ),
    ]
