# Generated by Django 5.0.2 on 2024-02-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_slot'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient'),
        ),
    ]
