# Generated by Django 5.0.2 on 2024-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_date_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='patient_appointment_documents/'),
        ),
    ]
