# Generated by Django 4.2.11 on 2024-03-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_start_consultation'),
        ('consultation', '0002_alter_consultation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
    ]
